#baseURL = "http://example.org/"
languageCode = "en-us"
title = "aecepoglu"
baseurl = "/"
theme = "er"
defaultContentLanguage = "tr"

[params]
	showtoc = false
	showTagCloud = false

[languages]
	[languages.en]
		languageName = "English"
	[languages.tr]
		languageName = "Türkçe"
